# .md2confl.yml
url: https://fmnapoli.atlassian.net
space: DDS
email: fmnapoli@gmail.com
force: true
write-marker: true

documents:
  - input: README.md
    title: "md2confl"

  - input: docs/
    parent-id: "589826"
